version: "3.8"

services:
  homeserver:
    image: homeserver:latest
    container_name: homeserver
    privileged: true
    cap_add:
      - NET_ADMIN
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/damo/Documents/projects/homeserver/neo/DATA/AppData:/home/damo/Documents/projects/homeserver/neo/DATA/AppData
      - /home/damo/Documents/projects/homeserver/neo/DATA:/home/damo/Documents/projects/homeserver/neo/DATA
      - /home/damo/Documents/projects/homeserver/neo/DATA/Media:/home/damo/Documents/projects/homeserver/neo/DATA/Media
      - /home/damo/.docker/config.json:/root/.docker/config.json
    command: /init
    restart: unless-stopped
